name: Publicar en RRSS

# Se ejecuta dos veces al día, a las 6:00 y a las 18:00 UTC
# (corresponde a las 8:00 y 19:00 hora peninsular española durante el horario de invierno)
# (corresponde a las 9:00 y 20:00 hora peninsular española durante el horario de verano)
on:
  schedule:
    - cron: '0 7 * * *'
    - cron: '0 18 * * *'        
  # También permite ejecutarlo manualmente desde la web de GitHub
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    # Solo necesitamos leer el código, no escribir
    permissions:
      contents: read

    steps:
      - name: Descargar código del repositorio
        uses: actions/checkout@v4

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar librerías
        run: |
          pip install -r requirements.txt

      - name: Publicar en RRSS
        env:
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: python instagram.py
